<mapla>
    <glowa>
        <oko>
			<title>wonsz</title>
        </oko>
        <oko>
        </oko>
    </glowa>

    <reka>
    </reka>

    <reka>
    </reka>

    <noga>
    </noga>
    <noga>
    </noga>

    <ogon>
    </ogon>
</mapla>